source("config.R")

run_generate_figures_stage <- function(scenario = get_amr_scenario()) {
  message("[generate_figures] scenario: ", scenario)

  if (scenario %in% c("main", "hic", "lmic")) {
    require_inputs(c(
      "Outputs/database_gradients_pathogen_ATC3_PCA_canonical_weighted_main.csv",
      "Outputs/database_gradients_ATC3_PCA_canonical_weighted_all.csv",
      "Outputs/database_gradients_bootstraps_ATC3_PCA_canonical_weighted_all.csv"
    ), stage = "generate_figures")
  } else if (scenario == "hospital_nagorsen") {
    require_input(
      "Outputs/Nagorsen_gradients_pathogen_ATC3_PCA_canonical_hospital_to_all_filtered.csv",
      stage = "generate_figures"
    )
  }

  if (scenario %in% c("main", "hic", "lmic")) {
    burden_files_present <- warn_missing_inputs(c(
      AMR_CONFIG$burden_inputs$figure3_pathogen,
      AMR_CONFIG$burden_inputs$figure3_optimistic,
      AMR_CONFIG$burden_inputs$figure3_pessimistic
    ), stage = "generate_figures")
  } else {
    burden_files_present <- FALSE
  }

  dir.create(AMR_CONFIG$output_dirs$manuscript, recursive = TRUE, showWarnings = FALSE)
  dir.create(AMR_CONFIG$output_dirs$slides, recursive = TRUE, showWarnings = FALSE)

  if (scenario %in% c("main", "hic", "lmic", "hospital_nagorsen")) {
    message("[generate_figures] Running canonical figure module...")
    source(AMR_CONFIG$canonical$figure_module)
    write_figure_metadata("Figure1.pdf",
      inputs = c("Outputs/database_gradients_pathogen_ATC3_PCA_canonical_weighted_main.csv",
                 "Outputs/database_gradients_bootstraps_ATC3_PCA_canonical_weighted_all.csv"),
      scenario = scenario)
    write_figure_metadata("Figure2.pdf",
      inputs = c("Outputs/database_gradients_pathogen_PCA_canonical_weighted_all.csv",
                 "Outputs/database_gradients_bootstraps_pathogen_PCA_canonical_weighted_all.csv"),
      scenario = scenario)
    if (burden_files_present) {
      write_figure_metadata("Figure3.pdf",
        inputs = c(AMR_CONFIG$burden_inputs$figure3_pathogen,
                   AMR_CONFIG$burden_inputs$figure3_optimistic,
                   AMR_CONFIG$burden_inputs$figure3_pessimistic),
        scenario = scenario)
    }
    # Figure 4 is generated by plotting.R (generate_figure4()) when its burden
    # input CSVs are present (written by make burden).
    fig4_inputs_present <- warn_missing_inputs(c(
      AMR_CONFIG$burden_inputs$figure4_region,
      AMR_CONFIG$burden_inputs$figure4_gdp,
      AMR_CONFIG$burden_inputs$figure4_use,
      AMR_CONFIG$burden_inputs$lower_burden_region
    ), stage = "generate_figures")
    if (fig4_inputs_present) {
      write_figure_metadata("Figure4.pdf",
        inputs = c(AMR_CONFIG$burden_inputs$figure4_region,
                   AMR_CONFIG$burden_inputs$figure4_gdp,
                   AMR_CONFIG$burden_inputs$figure4_use),
        scenario = scenario)
    }
    # Supplementary Figure S1: pathogen elasticities HIC vs LMIC.
    # Generated by plotting.R when both HIC and LMIC pathogen model CSVs exist.
    suppfig_s1_inputs_present <- warn_missing_inputs(c(
      "Outputs/database_gradients_pathogen_ATC3_PCA_canonical_weighted_HIC.csv",
      "Outputs/database_gradients_pathogen_ATC3_PCA_canonical_weighted_LMIC.csv"
    ), stage = "generate_figures")
    if (suppfig_s1_inputs_present) {
      write_figure_metadata(
        file.path(AMR_CONFIG$output_dirs$slides, "Supplementary_Figure_S1_Slide_narrow.pdf"),
        inputs = c(
          "Outputs/database_gradients_pathogen_ATC3_PCA_canonical_weighted_HIC.csv",
          "Outputs/database_gradients_pathogen_ATC3_PCA_canonical_weighted_LMIC.csv"
        ),
        scenario = scenario)
    }
  }

  message("[generate_figures] done")
}
